version: "3"

services: 
    db:
        image: mysql
        restart: always
        env_file: 
            - .env
        environment: 
            MYSQL_DATABASE: 'saitynaiapi'
            MYSQL_USER: 'saitynaiapi'
            MYSQL_PASSWORD: '${USER_PASSWORD}'
            MYSQL_ROOT_PASSWORD: '${ROOT_PASSWORD}'
        ports:
            - '3306:3306'
    web:
        build: ./SaitynaiAPI
        ports:
            - "8000:80"
        depends_on:
            - db
        volumes:
            - "./SaitynaiAPI:/app"
        env_file: 
            - .env
    client:
        stdin_open: true
        build: ./saitynai
        ports:
            - "3000:3000"
        volumes:
            - "./saitynai:/front"
        depends_on: 
            - web